### ISSUE TITLE
Icon diffs reportedly taking 2017 years to complete

### ISSUE THREAD

**Issue by DamianX** [tgstation/IconDiffBot#47]
![image](https://user-images.githubusercontent.com/6307265/43040131-20a64b1c-8d3c-11e8-91d2-b22acd875627.png)

![firefox_2018-07-21_23-15-21](https://user-images.githubusercontent.com/6307265/43040138-4c54a5d8-8d3c-11e8-9d33-63340901dab0.png)

a) https://github.com/vgstation-coders/vgstation13/commit/1c48c8756996a5161d910531fa65930d3291bfcd

b) https://github.com/vgstation-coders/vgstation13/pull/18914/checks?check_run_id=8684258

**Comment by Cyberboss** [comment]
:thinking:

**Comment by Cyberboss** [comment]
Caused by #46 

Upstream fix: https://github.com/octokit/octokit.net/pull/1852
