### ISSUE TITLE
The located assembly's manifest definition does not match the assembly reference

### ISSUE THREAD

**Issue by PsiOmegaDelta** [tgstation/IconDiffBot#59]
The DMI [onmob_accessories.dmi](https://github.com/Baystation12/Baystation12/blob/d5d30634727bf5af72a902abc20ca9bde3976c35/icons/mob/onmob/onmob_accessories.dmi) could not be rendered due to the error referenced at the bottom of this issue ticket.

a) The commit that caused the failure
https://github.com/Baystation12/Baystation12/pull/28254/commits/d5d30634727bf5af72a902abc20ca9bde3976c35

b) The failed check run
https://github.com/Baystation12/Baystation12/pull/28254/checks

```
System.IO.FileLoadException: Could not load file or assembly 'MetadataExtractor, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'MetadataExtractor, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'
   at IconDiffBot.Core.DiffGenerator.StreamToMetadataString(Stream stream)
   at IconDiffBot.Core.DiffGenerator.GenerateDiffs(Stream before, Stream after)
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass12_0.<<GenerateDiffs>g__DiffDmi|0>d.MoveNext()
```

**Comment by AffectedArc07** [comment]
Fixed. Please re-run the check.
