### ISSUE TITLE
Diffs generating for over an hour

### ISSUE THREAD

**Issue by ghost** [tgstation/IconDiffBot#68]
Note that inconsistencies/errors in renderings should be reported on the upstream repository: https://github.com/SpaceManiac/SpacemanDMM

Please leave permanent links to:

a) The commit that caused the failure
https://github.com/tgstation/tgstation/commit/6b79f58cdfc6ed1c12a07ced7d8e9570acfa59cf
b) The failed check run
https://github.com/tgstation/tgstation/runs/2582693340

**Comment by AffectedArc07** [comment]
Push a new commit, it likely crashed during generation

**Comment by ghost** [comment]
I did.

**Comment by AffectedArc07** [comment]
Not a code issue

**Comment by Cyberboss** [comment]
Might be, how did it crash?

**Comment by AffectedArc07** [comment]
> Might be, how did it crash?

Kevinzz

**Comment by Cyberboss** [comment]
They're a catalyst, not a cause though

**Comment by AffectedArc07** [comment]
> They're a catalyst, not a cause though

Keep in mind anything causing large memory usages on my server will make linux just shoot random processes till it has enough. So a mass MDB render can take out IDB, and vice versa.

**Comment by Cyberboss** [comment]
Fair
